"use strict";
const message = "Hello TypeScript!";
console.log(message);
const message2 = "Hello TypeScript!";
console.log(message2);
const message3 = "Hello TypeScript!";
console.log(message3);
const message4 = "Hello TypeScript!";
console.log(message4);
const message5 = "Hello TypeScript!";
console.log(message5);
